module.exports={
    google:{
        client_id:'***',
        client_secret:'***',
        callback_url:'http://localhost:3000/auth/google/callback'
    },
    facebook:{
        client_id:'***',
        client_secret:'**',
        callback_url:'http://localhost:3000/auth/facebook/callback'
    },
    twitter:{
        consumerKey:'****',
        consumerSecret:'***',
        callbackURL:'http://localhost:3000/auth/twitter/callback'
    },
    token_secret:"sidranerocks"
};
